import { CompoundingStageData } from "./compounding.types";

export const COMPOUNDING_STAGES: CompoundingStageData[] = [
  {
    id: "capture",
    number: "01",
    name: "CAPTURE",
    purpose: "Capture opportunities, ideas, audience signals, customer data, market shifts, and new assets.",
    description: "Continuously crawl and ingest global market changes, code repositories, and asset price fluctuations.",
    liveMetric: "4,209 Signals/sec",
    metrics: [
      { label: "Signals Captured", value: "842,912" },
      { label: "Opportunities Detected", value: "1,248" },
      { label: "Data Sources Connected", value: "32" },
    ],
    status: "idle",
    aiRecommendation: "Establish content analytics pipelines to capture audience interest signals and automatically route them to product creation queues.",
    primaryAction: { label: "Open Capture Systems", href: "/dashboard" },
    secondaryAction: { label: "View Related Moguls", href: "/moguls/intelligence" },
  },
  {
    id: "analyze",
    number: "02",
    name: "ANALYZE",
    purpose: "Transform raw information into intelligence, priorities, forecasts, and decisions.",
    description: "Multi-agent consensus protocols sift signals, score confidence levels, and identify high-value execution steps.",
    liveMetric: "99.8% Accuracy",
    metrics: [
      { label: "Signals Analyzed", value: "249,120" },
      { label: "AI Confidence Level", value: "98.7%" },
      { label: "Insights Generated", value: "3,591" },
    ],
    status: "idle",
    aiRecommendation: "Run cross-correlation checks on growth rate anomalies across division 03 to optimize direct acquisition parameters.",
    primaryAction: { label: "Open Analysis Engine", href: "/dashboard" },
    secondaryAction: { label: "View Related Moguls", href: "/moguls/ai" },
  },
  {
    id: "compound",
    number: "03",
    name: "COMPOUND",
    purpose: "Turn data, capital, content, knowledge, and automation into reusable leverage.",
    description: "Convert every line of code, document, and dollar into a recurring asset that feeds back into the loop.",
    liveMetric: "24.6% Compound Rate",
    metrics: [
      { label: "Systems Compounding", value: "12" },
      { label: "Automations Running", value: "148" },
      { label: "Capital Cycles Active", value: "4" },
    ],
    status: "idle",
    aiRecommendation: "The strongest current compounding opportunity is converting the Growth Engine analytics into automated content, CRM, and capital allocation workflows.",
    primaryAction: { label: "Open Compounding Systems", href: "/dashboard" },
    secondaryAction: { label: "View Related Moguls", href: "/moguls/capital" },
  },
  {
    id: "multiply",
    number: "04",
    name: "MULTIPLY",
    purpose: "Scale winning systems through automation, distribution, partnerships, capital, and media.",
    description: "Replicate optimized workflows across new markets, audiences, and channels to accelerate yield.",
    liveMetric: "8.4x Multiplier",
    metrics: [
      { label: "Growth Multiple", value: "8.4x" },
      { label: "Active Channels", value: "14" },
      { label: "Replicated Systems", value: "8" },
    ],
    status: "idle",
    aiRecommendation: "Deploy the newly synthesized marketing pipelines globally to compound audience distributions at zero variable cost.",
    primaryAction: { label: "Open Scale Engine", href: "/dashboard" },
    secondaryAction: { label: "View Related Moguls", href: "/moguls/venture" },
  },
  {
    id: "dominate",
    number: "05",
    name: "DOMINATE",
    purpose: "Convert scale into category leadership, defensibility, ownership, and market power.",
    description: "Secure sector monopoly, compound switching costs, and lock in ecosystem-wide distribution pipelines.",
    liveMetric: "Category Leader",
    metrics: [
      { label: "Market Position", value: "#1" },
      { label: "Category Share", value: "42.5%" },
      { label: "Empire Strength Index", value: "98/100" },
    ],
    status: "idle",
    aiRecommendation: "Expand network locks around our proprietary data storage APIs to reinforce barriers against competing multi-agent suites.",
    primaryAction: { label: "View Market Position", href: "/dashboard" },
    secondaryAction: { label: "View Related Moguls", href: "/moguls/strategy" },
  },
];
